config/routes.rb
NitchApp::Application.routes.draw do
  get "comments/show"

  get "posts/show"

  constraints(subdomain: 'www') do
    resources :sessions, controller: 'user_sessions'
    resources :users

    match 'signup' => 'users#new', as: :signup
    match 'login' => 'user_sessions#new', as: :login
    match 'logout' => 'user_sessions#destroy', as: :logout

    match 'bar/:nitch_name'   => 'dashboard#bar', as: :nitch_bar
    root to: 'dashboard#index', as: :dashboard
  end

  constraints(subdomain: /.*/) do
    resources :archives, name_prefix: nil, path_prefix: nil, controller: 'nitch/archives'
    resources :posts, name_prefix: nil, path_prefix: nil, controller: 'nitch/posts'
    resources :comments, name_prefix: nil, path_prefix: nil, controller: 'nitch/comments'

    match 'a/:archive_key/:archive_slug/:post_key/:post_slug/:key' => 'nitch/comments#show', as: :comment
    match 'a/:archive_key/:archive_slug/:key/:slug' => 'nitch/posts#show', as: :post
    match 'a/:key/:slug' => 'nitch/archives#show', as: :archive
    match 'a' => 'nitch/archives#index', as: :all_archives

    match 'follow' => 'nitch#follow', as: 'follow_nitch'

    root to: 'nitch#show', as: :nitch
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    # unless logged_in?
      render :welcome
    # end
  end

  def bar
    @nitch = Nitch.find_by_name(params[:nitch_name])

    render layout: false
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/bar.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    %title= content_for?(:title) ? yield(:title) : "Nitch"

    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"

    = stylesheet_link_tag "application", :media => "all"

    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

    %base(target="_parent")

  %body
    .nitch-bar-container
      .nitch-bar
        - if logged_in? && @nitch
          = link_to follow_nitch_url(subdomain: @nitch.name), class: 'btn btn-mini' do
            %i.icon-plus
            = "Join #{@nitch.title}"

          = link_to dashboard_url, class: 'btn btn-mini' do
            %i.icon-home
            Dashboard

          / = link_to dashboard_url do
          /   %span.badge.badge-info
          /     0

        - elsif @nitch
          = link_to login_url(nitch_name: @nitch.name), class: 'btn btn-mini' do
            %i.icon-plus
            = "Join #{@nitch.title}"
          = link_to signup_url(nitch_name: @nitch.name), class: 'btn btn-mini' do
            %i.icon-user
            Signup

    = javascript_include_tag "application"

app/views/dashboard/welcome.html.haml
#welcome
  .container
    .row
      .span12
        %h1
          Nitchio

        %h2.lead
          Welcome. Find your niche.
    .row
      - Nitch.all.each do |nitch|
        = link_to nitch_url(subdomain: nitch.name) do
          .nitch.span2.well
            %h3.name=  nitch.title
            .description= simple_format nitch.description