config/routes.rb
NitchApp::Application.routes.draw do
  get "comments/show"

  get "posts/show"

  constraints(subdomain: 'www') do
    resources :sessions, controller: 'user_sessions'
    resources :users

    match 'signup' => 'users#new', as: :signup
    match 'login' => 'user_sessions#new', as: :login
    match 'logout' => 'user_sessions#destroy', as: :logout

    match 'bar/:nitch_name'   => 'dashboard#bar', as: :nitch_bar
    root to: 'dashboard#index', as: :dashboard
  end

  constraints(subdomain: /.*/) do
    resources :archives, name_prefix: nil, path_prefix: nil, controller: 'nitch/archives'
    resources :posts, name_prefix: nil, path_prefix: nil, controller: 'nitch/posts'
    resources :comments, name_prefix: nil, path_prefix: nil, controller: 'nitch/comments'

    match 'a/:archive_key/:archive_slug/:post_key/:post_slug/:key' => 'nitch/comments#show', as: :comment
    match 'a/:archive_key/:archive_slug/:key/:slug' => 'nitch/posts#show', as: :post
    match 'a/:key/:slug' => 'nitch/archives#show', as: :archive
    match 'a' => 'nitch/archives#index', as: :all_archives

    match 'follow' => 'nitch#follow', as: 'follow_nitch'

    root to: 'nitch#show', as: :nitch
  end
end

app/models/archive.rb
class Archive < ActiveRecord::Base
  attr_accessible :title, :body

  validates_presence_of :slug, :title, :body, :user_id, :nitch_id

  belongs_to :nitch, counter_cache: true
  belongs_to :user, counter_cache: true

  has_many :posts
  has_many :comments

  before_validation :generate_slug
  after_create :generate_key

  def generate_slug
    self.slug = title.parameterize
  end

  def generate_key
    update_attribute :key, 'a' + self.id.to_s(36)
  end
end

app/models/nitch.rb
class Nitch < ActiveRecord::Base
  attr_accessible :name, :title, :description, :privacy

  validates_presence_of :name, :title, :privacy
  validates_uniqueness_of :name, :title
  validates_exclusion_of :name, :in => Settings.reserved_subdomains
  validates_inclusion_of :privacy, :in => Settings.nitch_privacy

  has_settings

  # has_and_belongs_to_many :users
  has_many :archives
  has_many :posts
  has_many :comments

  after_create :set_defaults!

  def accessible_by?(user)
    return true if %w(public invite).include?(privacy)
    return true if user && has_user?(user)
    return false
  end

  def has_user?(user)
    return true if users.include?(user)
  end

  def set_defaults!
    self.settings.archive_name = 'Archive'
  end
end

app/controllers/nitch/archives_controller.rb
class Nitch::ArchivesController < Nitch::BaseController
  layout 'nitch'
  before_filter :require_user, only: [:new, :create]

  def index
    @user = User.find_by_key(params[:key]) if params[:key]
  end

  def show
    @archive = current_nitch.archives.where(key: params[:key], slug: params[:slug]).first

    unless @archive
      redirect_to nitch_url
    end
  end

  def new
    @archive = Archive.new
  end
  
  def create
    @archive = Archive.new(params[:archive])

    @archive.nitch = current_nitch
    @archive.user  = current_user

    if @archive.save
      redirect_to archive_url(key: @archive.key, slug: @archive.slug)
    else
      render :new
    end
  end
end

app/controllers/nitch/base_controller.rb
class Nitch::BaseController < ApplicationController
  before_filter :set_and_load_nitch

  helper_method :current_nitch

  private
  def nitch_not_found
    raise ActionController::RoutingError.new('Nitch Not Found')
  end

  def archive_not_found
    raise ActionController::RoutingError.new('Archive Not Found')
  end

  def post_not_found
    raise ActionController::RoutingError.new('Comment Not Found')
  end

  def comment_not_found
    raise ActionController::RoutingError.new('Comment Not Found')
  end

  def nitch_inaccessible
    raise ActionController::RoutingError.new('Nitch Inaccessible')
  end

  def page_not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def current_nitch
    return @current_nitch if defined?(@current_nitch)
  end

  def set_and_load_nitch
    if request.subdomain.present? && request.subdomain == 'www'
      goto_dashboard
    elsif request.subdomain.present?
      @current_nitch = Nitch.where(name: request.subdomain.downcase).first || goto_dashboard
    else
      goto_dashboard
    end
  end

  def verify_nitch_privacy
    return true
    # unless current_nitch && current_nitch.accessible_by?(current_user)
    #   redirect_to private_nitch_path
    # 
    #   return false
    # end
  end
end

app/controllers/nitch/comments_controller.rb
class Nitch::CommentsController < Nitch::BaseController
  layout 'nitch'
  before_filter :load_post_and_archive
  before_filter :require_user, only: [:new, :create]

  def show
    @comment = @post.comments.where(key: params[:key]).first

    unless @comment
      redirect_to post_url(@post.key, @post.slug)
    end
  end

  def new
  end
  
  def create
    @comment = if params[:parent_id]
      parent = @post.comments.find(params[:parent_id])
      parent.children.new(params[:comment])
    else
      Comment.new(params[:comment])
    end

    @comment.nitch = current_nitch
    @comment.user  = current_user
    @comment.archive = @archive
    @comment.post = @post

    if @comment.save
      redirect_to post_url(archive_key: @archive.key, archive_slug: @archive.slug, key: @post.key, slug: @post.slug)
    else
      render :new
    end
  end

  protected
  def load_post_and_archive
    if params[:archive_id]
      @archive = current_nitch.archives.find(params[:archive_id])
    else
      @archive = current_nitch.archives.where(key: params[:archive_key], slug: params[:archive_slug]).first
    end
    return archive_not_found unless @archive

    if params[:post_id]
      @post = @archive.posts.find(params[:post_id])
    else
      @post = @archive.posts.where(key: params[:post_key], slug: params[:post_slug]).first
    end
    return post_not_found unless @post
  end
end

app/controllers/nitch/posts_controller.rb
class Nitch::PostsController < Nitch::BaseController
  layout 'nitch'
  before_filter :load_archive
  before_filter :require_user, only: [:new, :create]

  def show
    @post = @archive.posts.where(key: params[:key], slug: params[:slug]).first

    unless @post
      redirect_to archive_url(@archive.key, @archive.slug)
    end
  end

  def new
  end
  
  def create
    @post = Post.new(params[:post])

    @post.nitch = current_nitch
    @post.user  = current_user
    @post.archive = @archive

    if @post.save
      redirect_to post_url(archive_key: @archive.key, archive_slug: @archive.slug, key: @post.key, slug: @post.slug)
    else
      render :new
    end
  end

  protected
  def load_archive
    if params[:archive_id]
      @archive = current_nitch.archives.find(params[:archive_id])
    else
      @archive = current_nitch.archives.where(key: params[:archive_key], slug: params[:archive_slug]).first
    end

    archive_not_found unless @archive
  end
end

app/controllers/nitch_controller.rb
class NitchController < Nitch::BaseController
  before_filter :verify_nitch_privacy, except: :private

  def show
    # unless logged_in?
    #   redirect_to join_nitch_path
    # end
  end
end

app/helpers/nitch/archives_helper.rb
module Nitch::ArchivesHelper
  def archive_breadcrumb(archive = nil, post = nil, comment = nil)
    render partial: 'nitch/archives/breadcrumb', locals: { archive: archive, post: post, comment: comment }
  end

  def render_archive(archive, options = {})
    render partial: 'nitch/archives/archive', object: archive, locals: { options: options }
  end
end

app/helpers/nitch/base_helper.rb
module Nitch::BaseHelper
end

app/helpers/nitch/comments_helper.rb
module Nitch::CommentsHelper
  def render_comment(comment, options = {})
    render partial: 'nitch/comments/comment', object: comment, locals: { options: options }
  end
end

app/helpers/nitch/posts_helper.rb
module Nitch::PostsHelper
  def render_post(post, options = {})
    render partial: 'nitch/posts/post', object: post, locals: { options: options }
  end
end

app/helpers/nitch_helper.rb
module NitchHelper
  def activity_feed_items
    [current_nitch.archives, current_nitch.posts].flatten.compact.sort_by(&:created_at).reverse
  end

  def render_activity_feed_item(item)
    case item
    when Archive
      render_archive item, link: true
    when Post
      render_post item
    when Comment
      # render_comment item, archive: item.archive, post: item.post, parent: item.parent
    end
  end
end

app/views/nitch/archives/_archive.html.haml
.row
  / .span2
  /   %ul.thumbnails
  /     %li.span2.thumbnail
  /       - if options[:link]
  /         = link_to image_tag('http://placehold.it/260x180'), archive_url(archive.key, archive.slug)
  /       - else
  /         = image_tag('http://placehold.it/260x180')
  .span10
    .title
      - if options[:link]
        %h2= link_to archive.title, archive_url(archive.key, archive.slug)
      - else
        %h2= archive.title
    .body= simple_format archive.body

app/views/nitch/archives/_breadcrumb.html.haml
%ul.breadcrumb
  %li
    = link_to current_nitch.settings.archive_name.pluralize, all_archives_url
    - if archive
      %span.divider &raquo;
  - if archive
    %li
      = link_to archive.title, archive_url(archive.key, slug: archive.slug)
      - if post
        %span.divider &raquo;
  - if post
    %li(style="overflow: hidden;")
      = link_to truncate(post.title, length: 40), post_url(post.archive.key, post.archive.slug, post.key, post.slug)
      - if comment
        %span.divider &raquo;
  - if comment
    %li(style="overflow: hidden;")
      = link_to truncate(comment.body, length: 40), comment_url(comment.post.archive.key, comment.post.archive.slug, comment.post.key, comment.post.slug, comment.key)

app/views/nitch/archives/_new_modal.html.haml
#new-archive-form.modal.fade.hide
  .modal-header
    %h3
      = "New #{current_nitch.settings.archive_name}"
  .modal-body
    = form_for Archive.new, url: archives_url do |f|
      = render partial: 'nitch/archives/form', locals: { f: f }
  .modal-footer
    %button.btn(data-dismiss="modal") Cancel
    %button#new-archive-submit.btn.btn-primary Save

app/views/nitch/archives/index.html.haml
.row
  .span10
    = archive_breadcrumb

.row
  .span8
    .btn-group
      = link_to('#', {class: 'btn active'}) do
        %i.icon-fire
        Hottest
      = link_to('#', {class: 'btn'}) do
        %i.icon-time
        Newest
      = link_to('#', {class: 'btn'}) do
        %i.icon-eye-open
        Discussed
  .span2
    .btn-group.pull-right
      = link_to('#', {class: 'btn active'}) do
        %i.icon-th-list
      = link_to('#', {class: 'btn'}) do
        %i.icon-th

.row
  .span10
    .archives
      - current_nitch.archives.each do |archive|
        = render_archive archive, link: true

app/views/nitch/archives/new.html.haml
.row
  .span8
    %h2.page-header= "New #{current_nitch.settings.archive_name}"
    = form_for @archive, url: archives_url do |f|
      = render partial: 'nitch/archives/form', locals: { f: f }
      .form-actions
        = f.submit 'Save', class: 'btn btn-primary'

app/views/nitch/archives/show.html.haml
.row
  .span10
    = archive_breadcrumb @archive

= render_archive @archive

.row
  .span10
    %ul.nav.nav-tabs
      %li.active
        = link_to('#') do
          Updates

/ .row
/   .span3
/     .btn-group
/       = link_to('#', {class: 'btn active'}) do
/         %i.icon-fire
/         Hottest
/       = link_to('#', {class: 'btn'}) do
/         %i.icon-time
/         Newest
/       = link_to('#', {class: 'btn'}) do
/         %i.icon-eye-open
/         Discussed

.row
  .span2
    #new-post-button
      = link_to('#new-post-form', 'class' => 'btn btn-primary', 'data-toggle' => 'modal') do
        %i.icon-plus-sign
        New Post

- content_for :modal do
  = render partial: 'nitch/posts/new_modal', locals: { archive: @archive }

.row
  .span10
    .posts
      - @archive.posts.each do |post|
        = render_post post, comments_count: true