config/routes.rb
NitchApp::Application.routes.draw do
  get "comments/show"

  get "posts/show"

  constraints(subdomain: 'www') do
    resources :sessions, controller: 'user_sessions'
    resources :users

    match 'signup' => 'users#new', as: :signup
    match 'login' => 'user_sessions#new', as: :login
    match 'logout' => 'user_sessions#destroy', as: :logout

    match 'bar/:nitch_name'   => 'dashboard#bar', as: :nitch_bar
    root to: 'dashboard#index', as: :dashboard
  end

  constraints(subdomain: /.*/) do
    resources :archives, name_prefix: nil, path_prefix: nil, controller: 'nitch/archives'
    resources :posts, name_prefix: nil, path_prefix: nil, controller: 'nitch/posts'
    resources :comments, name_prefix: nil, path_prefix: nil, controller: 'nitch/comments'

    match 'a/:archive_key/:archive_slug/:post_key/:post_slug/:key' => 'nitch/comments#show', as: :comment
    match 'a/:archive_key/:archive_slug/:key/:slug' => 'nitch/posts#show', as: :post
    match 'a/:key/:slug' => 'nitch/archives#show', as: :archive
    match 'a' => 'nitch/archives#index', as: :all_archives

    match 'follow' => 'nitch#follow', as: 'follow_nitch'

    root to: 'nitch#show', as: :nitch
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  find_by_login_method :find_by_username_or_email
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :load_nitch
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])

    if @user_session.save
      flash[:notice] = "Login successful!"

      redirect_back_or_default @nitch ? nitch_url(subdomain: @nitch.name) : dashboard_url
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy

    flash[:notice] = "Logout successful!"

    redirect_back_or_default dashboard_url
  end

  private
  def load_nitch
    @nitch = params[:nitch_name] ? Nitch.find_by_name(params.delete(:nitch_name)) : nil
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.haml
.container
  .row
    .span4.offset4
      %h1
        Nitch Signup
      Not a User?
      - if @nitch
        = link_to 'Signup', signup_url(nitch_name: @nitch.name)
      - else
        = link_to 'Signup', signup_url
      
      = form_for @user_session, url: @nitch ? sessions_path(nitch_name: @nitch.name) : sessions_path do |f|
        = f.label 'Username', for: :username
        = f.text_field :username

        = f.label 'Password', for: :password
        = f.password_field :password

        .form-actions
          = f.submit 'Login', class: 'btn btn-primary'