config/routes.rb
NitchApp::Application.routes.draw do
  get "comments/show"

  get "posts/show"

  constraints(subdomain: 'www') do
    resources :sessions, controller: 'user_sessions'
    resources :users

    match 'signup' => 'users#new', as: :signup
    match 'login' => 'user_sessions#new', as: :login
    match 'logout' => 'user_sessions#destroy', as: :logout

    match 'bar/:nitch_name'   => 'dashboard#bar', as: :nitch_bar
    root to: 'dashboard#index', as: :dashboard
  end

  constraints(subdomain: /.*/) do
    resources :archives, name_prefix: nil, path_prefix: nil, controller: 'nitch/archives'
    resources :posts, name_prefix: nil, path_prefix: nil, controller: 'nitch/posts'
    resources :comments, name_prefix: nil, path_prefix: nil, controller: 'nitch/comments'

    match 'a/:archive_key/:archive_slug/:post_key/:post_slug/:key' => 'nitch/comments#show', as: :comment
    match 'a/:archive_key/:archive_slug/:key/:slug' => 'nitch/posts#show', as: :post
    match 'a/:key/:slug' => 'nitch/archives#show', as: :archive
    match 'a' => 'nitch/archives#index', as: :all_archives

    match 'follow' => 'nitch#follow', as: 'follow_nitch'

    root to: 'nitch#show', as: :nitch
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    %title= content_for?(:title) ? yield(:title) : "Nitchio"

    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"

    = stylesheet_link_tag "application", :media => "all"

    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .container
      .content
        = yield

      %footer

    = javascript_include_tag "application"


app/views/layouts/nitch.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    %title= content_for?(:title) ? yield(:title) : "Nitchio"

    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"

    = stylesheet_link_tag "application", :media => "all"

    %link(href="/images/favicon.ico" rel="shortcut icon")
    %link(href="/images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="/images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="/images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    %iframe#nitch-bar{ src: nitch_bar_url(subdomain: 'www', nitch_name: current_nitch.name) }
    #nitch-container-outer
      .container
        #nitch-container
          .row
            .span10
              %h1.logo
                %span= current_nitch.title
          .row
            .span2
              #nitch-sidebar-left.sidebar.well
                %ul.nav.nav-list
                  %li{ class: class_if_path_matches('active', /\A#{nitch_path}\Z/) }
                    = link_to nitch_url do
                      %i.icon-home
                      Activity Feed
                  %li{ class: class_if_path_matches('active', /\A#{all_archives_path}\Z/) }
                    = link_to all_archives_url do
                      %i.icon-list
                      = current_nitch.settings.archive_name.pluralize
                  %li
                    = link_to '' do
                      %i.icon-user
                      Members
                  %li.divider
                  - if logged_in?
                    %li.nav-header
                      = "My #{current_nitch.settings.archive_name.pluralize}"
                    - current_user.archives.where(nitch_id: current_nitch.id).each do |archive|
                      %li{ class: class_if_path_matches('active', /\A#{archive_path(archive.key, archive.slug)}/) }
                        = link_to archive.title, archive_url(archive.key, archive.slug)

                    = link_to new_archive_url, style: 'display: block; margin-top: 5px' do
                      %span.label
                        %i.icon-plus
                        Add
            .span10
              #nitch-content
                = yield

    %footer

    = yield(:modal) if content_for?(:modal)
    = javascript_include_tag "application"
